version: '3'
services:
    web:
        image: vulnerables/web-dvwa
        ports:
            - "80:80"
    tester:
        build: ./tester
        command: "python3 tester/main.py"
        volumes:
            - .:/var/src/app
        privileged: true
        ports:
            - "4000:4000"
    # mongodb:
    #     image: mongo:4.0.3-xenial
    #     restart: always
    #     ports:
    #         - "27017:27017"
    #     environment:
    #         MONGO_INITDB_DATABASE: tester